#!/usr/bin/env php
<?php

require_once __DIR__.'/AlomKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;

$kernel = new AlomKernel('test', true);
$application = new Application($kernel);
$application->run();
